package com.redsamurai.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 28 18:45:19 EEST 2018
// ---------------------------------------------------------------------
public interface EmployeesView extends ViewObject {
    void processChangedRows();
}

