package com.redsamurai.model.views;


import com.redsamurai.model.views.common.EmployeesView;

import java.util.Iterator;

import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 28 17:26:58 EEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl implements EmployeesView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }
    
    public void processChangedRows() {
        Iterator iter = this.getEntityDef(0).getAllEntityInstancesIterator(this.getDBTransaction());
        
        while (iter.hasNext()) {
            EntityImpl eo = (EntityImpl) iter.next();
            
            if (!"default".equals(this.getRowStatus(eo.getEntityState()))) {
                System.out.println("KEY: " + eo.getKey() + " , STATUS: " + this.getRowStatus(eo.getEntityState()));   
            }
        }
    }
    
    private String getRowStatus(byte statusFlag) {
        if (statusFlag == EntityImpl.STATUS_INITIALIZED || statusFlag == EntityImpl.STATUS_NEW) {
            return "new";
        } else if (statusFlag == EntityImpl.STATUS_DELETED) {
            return "deleted";
        } else if (statusFlag == EntityImpl.STATUS_MODIFIED) {
            return "modified";
        }
        return "default";
    }
}

